jitsi, same as used at PUC
digitalocean/droplet-1-clicks pull request #41
Opened 2021-07-11 16:24 UTC by pachadotdev

2021-09-30 20:35 UTC, lottetreg commented
Hey @pachadotdev! Could you please add a description to this PR to explain these changes and the reasons for them? Thanks :)

2022-02-24 19:13 UTC, paulanunda requested changes

2022-02-24 19:13 UTC, paulanunda commented on jitsi-20-04/files/etc/update-motd.d/99-one-click
> +https://github.com/pachadotdev/droplet-1-clicks/tree/master/jitsi-20-04
Please remove the pachadotdev reference

2022-02-24 21:57 UTC, paulanunda approved these changes

2022-02-24 21:58 UTC, merged